# Generated by Django 4.0.1 on 2022-01-16 01:38

import Zeus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('name', models.CharField(max_length=24)),
                ('prodid', models.TextField(default=Zeus.models.generate_uid.__call__, primary_key=True, serialize=False)),
                ('calscale', models.TextField(default='GREGORIAN')),
                ('method', models.TextField(null=True)),
                ('version', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uid', models.TextField(default=Zeus.models.generate_uid.__call__, primary_key=True, serialize=False)),
                ('dtstart', models.DateTimeField()),
                ('dtend', models.DateTimeField()),
                ('summary', models.TextField()),
                ('dtstamp', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('contact', models.TextField(null=True)),
                ('related_to', models.TextField(null=True)),
                ('uri', models.URLField(max_length=2048, null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('sequence', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['dtstart'],
            },
        ),
    ]
