# Generated by Django 4.0.1 on 2022-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0002_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
    ]
