# Generated by Django 4.0.1 on 2022-01-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0002_event_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.TextField(),
        ),
    ]
