# Generated by Django 4.0.1 on 2022-01-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0003_calendar_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Zeus.calendar'),
        ),
    ]
