# Generated by Django 4.0.1 on 2022-01-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0003_alter_calendar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='_class',
            field=models.TextField(null=True),
        ),
    ]
