# Generated by Django 4.0.1 on 2022-01-16 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0004_event__class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='geo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Zeus.geo'),
        ),
    ]
