# Generated by Django 4.0.1 on 2022-01-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0005_geo_event_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
