# Generated by Django 4.0.1 on 2022-01-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0006_event_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resources',
            field=models.TextField(null=True),
        ),
    ]
