# Generated by Django 4.0.1 on 2022-01-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0007_alter_event_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['DTSTART']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='DTEND',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='DTSTART',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='SUMMARY',
        ),
    ]
