# Generated by Django 4.0.1 on 2022-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0008_alter_event_options_rename_end_time_event_dtend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='DESCRIPTION',
            field=models.TextField(blank=True),
        ),
    ]
