# Generated by Django 4.0.1 on 2022-01-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0008_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='ical',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
