# Generated by Django 4.0.1 on 2022-01-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0009_calendar_ical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='calscale',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='method',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='version',
        ),
    ]
