# Generated by Django 4.0.1 on 2022-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0010_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='DTSSTAMP',
            field=models.DateTimeField(default='2022-01-15 17:59:00+00:00'),
            preserve_default=False,
        ),
    ]
