# Generated by Django 4.0.1 on 2022-01-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0011_event_dtsstamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='UID',
            field=models.TextField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
