# Generated by Django 4.0.1 on 2022-01-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0011_remove_event__class_remove_event_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
