# Generated by Django 4.0.1 on 2022-01-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0012_remove_event_id_event_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['dtstart']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='DESCRIPTION',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='DTEND',
            new_name='dtend',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='DTSSTAMP',
            new_name='dtsstamp',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='DTSTART',
            new_name='dtstart',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='LOCATION',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='SUMMARY',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='UID',
            new_name='uid',
        ),
    ]
