# Generated by Django 4.0.1 on 2022-01-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0012_calendar_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geo',
        ),
    ]
