# Generated by Django 4.0.1 on 2022-01-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0013_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='related_to',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(),
        ),
    ]
