# Generated by Django 4.0.1 on 2022-01-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0013_delete_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
