# Generated by Django 4.0.1 on 2022-01-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0014_event_contact_event_related_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dtsstamp',
            new_name='dtstamp',
        ),
    ]
