# Generated by Django 4.0.1 on 2022-01-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0015_rename_dtsstamp_event_dtstamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uri',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
