# Generated by Django 4.0.1 on 2022-01-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0016_event_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
