# Generated by Django 4.0.1 on 2022-01-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0017_event_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
