# Generated by Django 4.0.1 on 2022-01-16 00:16

import Zeus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0019_event_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.TextField(default=Zeus.models.generate_uid, primary_key=True, serialize=False),
        ),
    ]
