# Generated by Django 4.0.1 on 2022-01-16 01:16

import Zeus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zeus', '0020_alter_event_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.TextField(default=Zeus.models.generate_uid.__call__, primary_key=True, serialize=False),
        ),
    ]
